### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by fafafafdafafa4r31413** [0xAlloc/Valorant-External-Always-Updated#2]
my antivirus detected the program is in my roaming appdata in my windows folder. So i'm assuming it a virus because it in my windows folder. I have never seen it get flagged before.
https://www.virustotal.com/gui/file/bea180f891b2c55210d91ff3d8fe40a246d7943362a7b21ab32509dcf2b3c7d1/detection

**Comment by 0xAlloc** [comment]
No, it isn't, that is why the source is posted. False AV(s) occur when you are doing kernel manipulation without a taggant or digi-cert. It will flag unless I change a few lines with the mapper. If you do not trust the compiled version, the source is open to use! 

I do understand the concern, but no, it is not a virus and I would not post the source if it was. The compiled version is most likely outdated anyway due to Valorant randomly updating.

**Comment by 0xAlloc** [comment]
Also, `roaming appdata` comes from the mapper generating a temp directory, vuln driver to map the driver needed for the usermode. Feel free to use DiE with any of the sources, and compiled apps.
